### ISSUE TITLE
Iterating over collections

### ISSUE THREAD

**Issue by SanderMertens** [cortexlang/cortex#14]
Iterating over collections is at the heart of working with collections. Because it is anticipated that this feature will be used extensively, it should be expressive, performant, intuitive and concise. It also has to be as uniform as possible for all the supported collection types. Additionally, it als has to be type-safe and its usage should preferably be verifiable at compile time.

When walking over a collection, somewhere something has to keep track of the iteration 'state'. To put simply: when iterating over a collection, I need to keep track of the element that I last iterated over to know where I need to go next. This state is from hereon referred to as the 'iterator'.

Currently iterators are not exposed through the type system. Arguably they don't need to be when all the language would allow for is iterating over the whole of a collection. Note that in the following example it is not apparent that an iterator is used (pseudo-code):
```
foreach element in collection: "$element";
```
Clearly there is something in the background that is keeping track of the state of the iteration, but a developer wouldn't see it. Theoretically, iterators could be completely handled by the virtual machine, intermediate code and parser. However, iterators (and the things you can do with it) make sense to have in the language (and language bindings) as well. Therefore iterators need to be captured in the type system.

There are two basic approaches. One changes the type system while the other one doesn't. I'll describe the latter first.

## Adding a builtin class

Consider creating a builtin class called 'iterator' in the lang scope. This class would be a generic iterator for all collection types. A (simplified) interface for this class could look like:
```
class Iterator::
   collection: any;
   bool hasNext();
   any next();
```
Using this could look like:
```
list{uint32} someList: 0, 1, 2, 3, 4, 5;
Iterator iter{someList};
while iter.hasNext:
    uint32 value = iter.next;
```
There are many downsides to this approach. For one, iterators would rely on the invocation of methods, which is not a necessity and therefore slower than what it could be. Because this is such a performance-critical part of the language this is a real issue and one that could not be fixed easily at a later stage.

The second downside is that it doesn't enforce compile time safety. Since the class is a generic iterator it has to rely on the 'any' type to store the collection- and return the element value. Aside from a small performance hit in the usage of any's, this is an issue as well.

The upside of this approach is that it doesn't require modifications to the core type system, which is nice on the short-term, but doesn't weigh up to the the previous considerations.

## Adding a new type

The second approach is adding a new type kind "ITERATOR" to the type system. A new type-kind proliferates to the language design since it has to define behavior and syntax for this new type. This allows for a lot of freedom in how iterators are implemented. A consideration is whether it should be a top-level type kind (like PRIMITIVE, COMPOSITE, COLLECTION) or a 2nd level kind (like INTERFACE, STRUCT, CLASS). That way, iterators could leverage some properties from functionality that already exists. 

The following code shows a potential iterator usage example:
```
list{uint32} myList: 0, 1, 2, 3, 4, 5;
iterator{uint32} iter = myList; // Compile-time safety
while iter.hasNext:
    uint32 value = iter.next; // Compiler can verify whether this is allowed
```

Further thought is required on how to map this in a way so that there is a good balance between reusing existing functionality and leveraging/extending the existing type system features in a way that is useful.

**Comment by jleeothon** [comment]
In an unofficial conversation, we agreed:
- That we may not want functions to be called for iterator advancing, object retrieval, etc., because it adds a layer (a call to the stack?) of complexity at the cost of performance. Please elaborate on this, @SanderMertens 
- In the most common use case for iterators (i.e. for-each loops), iterators themselves are to be hidden from the end programmer, but we do want to support manual iterations (i.e. declaring iterators and moving them manually).
- The grammar should be independent of the underlying implementation. Because iterators are a kind of their own, we may provide ad-hoc operators such as `iter++` instead of functions, `iter.next()`.

However, I'm wondering, the code to handle these actions (iterator progress, object retrieval) would ultimately be C functions. Where should these reside? Should they reside in `cx_iterator.c`?

**Comment by jleeothon** [comment]
Let me try to call out a few example use cases for iterators...
Reminder: there would be extra grammar features for short circuiting the method call Cortex-level.

```
// An iterator as an object
list{int32} myNumberList: 1, 2, 3, 4
iterator numberIterator: int32;
numberIterator myNumberIterator: myNumberList
while myNumberIterator.hasNext():
```

**Comment by jleeothon** [comment]
The above assumes that the `iterator` class has an `elementType` member, and that an instance of `iterator` has a scope member `collection`, so that the instance of the instance of `iterator` has a `iterator` value member.

I don't see, however, how this could be possible, to define members for the final object in the class of the type.

**Comment by jleeothon** [comment]
Note that three similar but not equivalent idioms are:

Create an anonymous object (the assignment is for example purposes):
```
any i = iterator{int32}{myList}
```

Create a scoped object:
```
iterator{int32} myIterator: myList
// also
iterator numberIterator: uint32
numberIterator myNumberIterator: myList
```

Create a variable.
```
// Normal old syntax
iterator numberIterator: int32
var numberIterator myNumberIterator = numberIterator{myList} // var is optional in function scope
// Or new syntax/semantics:
var numberIterator myNumberIterator = myList
// or new syntax with anonymous types
var iterator{int32} myNumberIterator = myList
```

**Comment by jleeothon** [comment]
The above pieces of code suggests that `elementType` (e.g. `int32`) is a `member` in the scope of `iterator` and `collection` (e.g. `myList`) is a `member` in the scope of `NumberIterator`.
However we never declared any member in `NumberIterator`, what's more, we never opened its scope.
Can we confirm that this is a new semantic feature of iterator declaration for the iterator kind?
Where does the `collection` member reside in the Cortex source code?

**Comment by jleeothon** [comment]
Currently, implementation of iterator (C) structs produced by the `CX_ITERATOR` macro follow:
- For arrays
    - type: type of the array in Cortex
    - value: pointer to the beginning of the array
    - element: pointer to the next element to retrieve
- For lists:
    - type: type of the list in Cortex
    - value: the `cx_ll` object (it is a pointer to `cx_ll_s`)
    - element: a `cx_llNode` variable (we will not wrap around a `cx_iter` so that ultimately we may fuse together both iterating approaches)

**Comment by jleeothon** [comment]
The next iteration for the idea is:

- Call `next` if there is an assignment and the iterator is the right-hand side.
- Call `hasNext` if you read its value otherwise.

```
list{string} mylist: "a", "b", "c"

iterator{string} i: mylist

while i:
    string s = i;
    "$s"
```

Limitations

- You cannot assign (copy) an iterator to another one in normal ways. (Why would you even do that?)

```
class Dog::
    member i: iterator{string}

iterator{string} myiter = mylist

mydog.i = myiter // nope, doesn't work
mydog.i = mylist // well, that'd work
```
