### ISSUE TITLE
Set operation stopped working

### ISSUE THREAD

**Issue by jleeothon** [cortexlang/cortex#163]
Given the following piece of code:

```
list slist: string
slist mylist: "hey", "how", "are", "you"
iterator siter: string
siter i
i = mylist // complains here
```

The parser complains about the left side and right hand of the assignment being of different types.
```
test.cx:8:0: error: collection-expression types do not match (left: ::siter, right: ::slist)
   valid options:
      left: ::cortex::lang::string right: ::slist
      left: ::slist right: ::slist
test.cx: parsed with errors (1 errors, 0 warnings)
```

**Comment by SanderMertens** [comment]
What is the actual error message?

**Comment by jleeothon** [comment]
My bad!

**Comment by SanderMertens** [comment]
Seems like we lost some code in commit 101a2e91c7639d276c829cc516df80152152d8fd.

This commit adds code to cx_iterator.c that we added to support iterator assignments, but the accompanying code in Fast_Parser.c is absent. Unfortunately, that means that we'll have to rebuild this, as the code was never checked in.

**Comment by jleeothon** [comment]
Because we half-implemented the Next operation, I might not think it's ok to merge with master yet, but let's get this merged soon :).
