### ISSUE TITLE
Environment setup is dependent on current working directory

### ISSUE THREAD

**Issue by jleeothon** [cortexlang/cortex#194]
The `configure` file depends on the current working directory:

```
export CORTEX_HOME=`pwd`
```

It would be better to have this file take its location for `CORTEX_HOME` which would let the script work from wherever. This can be done with:

```
export CORTEX_HOME=`echo $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )`
```

**Comment by SanderMertens** [comment]
Is this issue solved in the referenced commit?
