### ISSUE TITLE
cxgen support for nested packages

### ISSUE THREAD

**Issue by jleeothon** [cortexlang/cortex#262]
**Problem statement**

Currently cxgen cannot handle (C) nested packages out of the box.

Example workflow: to create `::cortex::test` or `::cortex::profiling`, I used:

```
# from cortex home directory
cd packages/cortex
cxgen --package test --lang c
```

Then go to `test.cx` or `profiling.cx` and change the line `#package ::name` to `#package ::cortex::name`.

That one doesn't work right out of the box, but it's not a big hassle.

Now consider the case:

I want to make a package `::cortex::math::test`.

We can `cd` to `packages/cortex/math` then run `cxgen --package test --lang c`. Then change the package's full name to `::cortex::math::test`.

**Solution proposal**

The argument to cxgen --package could be a fully scoped name. That is, the name to be used in the `#package {::full::name}` statement. The folder should be named—at least by default— as the last part of the full name.

**Comment by SanderMertens** [comment]
This is fixed.

**Comment by SanderMertens** [comment]
Although the build system now passes fully scoped names to cxgen, creating a new package with a scoped name is still an issue. Is this related to #264 ?

**Comment by SanderMertens** [comment]
Proposed solution is to create a directory with the right-most name (in a scoped expression), while the .cx file in the directory will use the fully scoped name. For example:
```
cxgen --package ::cortex::web::test
```
will create a directory called `test`. The directory will contain a file with the following package header:
```
#package ::cortex::web::test
```
This will make it easier to build nested packages outside of the cortex installation directory (which is a bad idea anyway).
