### ISSUE TITLE
rake (+ cxgen) can't build sub package 

### ISSUE THREAD

**Issue by jleeothon** [cortexlang/cortex#264]
The two examples below could be two related but different issues.

- [ ] rake should build subpackages
- [ ] cxgen should generated nested scopes

# Example 1

![screenshot 2015-06-18 13 43 58](https://cloud.githubusercontent.com/assets/6202537/8239239/23728848-15c0-11e5-82e5-6052db56f61a.png)

There is a package called `test` inside the profiling package.

`cd` to the test subpackage. Run `rake clobber default`. Instead of generating files for implementation of the `TestProfiling` class, it only creates wrappers for the `::cortex::test` types.

The build system generated wrappers for dependency packages, but did not generate the current package.

# Example 2

Create an `autorun` package inside `$CORTEX_HOME/packages/cortex/test`. `cd` to this directory. Create a couple of types. Run `rake clobber default`. It doesn't build: complains there isn't an `autorun` package.

![screenshot 2015-06-18 13 50 41](https://cloud.githubusercontent.com/assets/6202537/8239391/18f9808c-15c1-11e5-8ebd-03dc6f642e2c.png)
![screenshot 2015-06-18 13 50 53](https://cloud.githubusercontent.com/assets/6202537/8239392/190dad5a-15c1-11e5-970a-82012fc3763c.png)

**Comment by SanderMertens** [comment]
This issue was fixed by issue #262
