### ISSUE TITLE
{package}.h is not generated for C packages

### ISSUE THREAD

**Issue by jleeothon** [cortexlang/cortex#266]
![screenshot 2015-06-18 15 02 06](https://cloud.githubusercontent.com/assets/6202537/8240833/1588342a-15cb-11e5-9329-aab64c9abf75.png)

The above error also occurs for packages with content inside them.

**Comment by SanderMertens** [comment]
Obviously this doesn't happen for each package (otherwise nothing would build anymore). Have you been able to find out what is different in the package you're trying to generate?

**Comment by jleeothon** [comment]
That is right. I checked whether or not it was able to build stuff. It *can* build other packages.

**Comment by jleeothon** [comment]
That is right. If I try to clobber then build everything, it works.

**Comment by jleeothon** [comment]
-- Logging my actions so I can go back --

- I switched back to branch SanderMertens.
- Created an empty package.
- Tried to build.
- Got error message saying it won't find autotest.h.
- Filled the package with the following:

```
#package ::autotest

int8 foo: 9

class bar::
    member hello: int32
    void world()
```
- Tried to build again. It builds now.

Going to try back in my branch.

**Comment by jleeothon** [comment]
(Haven't switched branches)

Now tried with this code:

```
#package ::autotest

int8 foo: 9
 
```

Failed again with the same error (didn't generate `autotest.h`).

**Comment by jleeothon** [comment]
Tried this one:

```
#package ::autotest

void bar()

```

Doesn't fail either.
