### ISSUE TITLE
Observer align function should not use scopeWalk

### ISSUE THREAD

**Issue by SanderMertens** [cortexlang/cortex#285]
When observers subscribe for DECLARE or DEFINE events, they will be aligned with all PERSISTENT objects that were already declared or defined. The code that performs the align does a scope walk over the scope subscribed for.

However, since the `scopeWalk` takes a lock on the scope, it is impossible for observers to modify the scope, for example declaring new objects, as that would result in a deadlock. Suggested to use the `scopeClaim` function that will return a linked list with all the objects in the scope at that moment in time and then unlocks the scope.

**Comment by jleeothon** [comment]
Should fix when merged with master.

**Comment by SanderMertens** [comment]
Yes please,merge with master.
