### ISSUE TITLE
Add asprintf to the core API

### ISSUE THREAD

**Issue by jleeothon** [cortexlang/cortex#298]
`asprintf` is a [GNU extension](http://linux.die.net/man/3/asprintf) not everywhere available. However, we will take good advantage of such function.

We can transform this idiom:

```C
int len = snprintf(NULL, 0, "hey %s", name);
char* s = malloc(len + 1);
sprintf(s, "hey %s", name);
```

into:

```C
char *s = NULL;
asprintf(&s, "hey %s", name);
```
Where it will not be available, we can use https://github.com/littlstar/asprintf.c instead

@SanderMertens suggests that we include a `asnprintf` flavor to the family.

For now I will almost merely add `asprintf` to our API, wrapped by `cx_asprintf`.

**Comment by SanderMertens** [comment]
Typo: we're adding asprintf to our API, wrapped *by* cx_asprintf.
