### ISSUE TITLE
Change cortex directory structure

### ISSUE THREAD

**Issue by SanderMertens** [cortexlang/cortex#309]
The directory structure of cortex needs to be changed to accommodate for environments where cortex is installed to a machine while a user is developing from a local directory.

Key issue to address is that while a user is developing, he shouldn't be required to do this with elevated privileges. Since the package repository is located in /usr/local/lib, packages can't be installed here without sudo-ing each build command, which is annoying.

Therefore, packages (and other artifacts) will be stored in a local package repository that will be stored in the users home folder ($HOME/.cortex). The cortex loader will search this location as well when looking for packages.

The `cortex install` command shall move the package from the home directory to the global repository. Ultimately, this global repository shall be synced with the online repository whenever possible. Therefore, when installing a package, this should be considered equivalent to a git commit.

The directories under `.cortex` shall look like this:
```
/0.2.0/bin/
/0.2.0/lib/
/0.2.0/generators/
/0.2.0/libraries/
/0.2.0/components/
/0.2.0/packages/
```

**Comment by jleeothon** [comment]
The structure described above is not still standing.
Instead, now bin/lib/include are the first level of division and components/generators/packages/etc are subdivisions of the former.
Isn't that right?

**Comment by SanderMertens** [comment]
The current implemented structure is correct. The structure that is described above was a first attempt. As we have discussed, the structure in .cortex will resemble how things are stored under /usr
