### ISSUE TITLE
Make `dbsh_stateStr` and `dbsh_attrStr` publicly available

### ISSUE THREAD

**Issue by jleeothon** [cortexlang/cortex#35]
From `dbsh.c`, the functions `dbsh_stateStr` and `dbsh_attrStr` could be made available for reuse as the standard way of representing the state and attributes of an object, for example for serializers.

Also, what should be a recommended size for the buffer? Lines 129 and 130 in dbsh.c (https://github.com/Seldomberry/Hyve/blob/master/tools/dbsh/src/dbsh.c) seem to suggest that the representation was different than it actually is.

Solution 1. We could define a global size constant, something like `#define STATE_STR_MAX (sizeof("S|W|O"))`. Cons: pollute the global namespace.

Solution 2. Let the functions internally handle the creation of a necessary buffers. Cons: buffer can be internally allocated and externally freed. 

Solution 3. Postpone this issue to merge it with defining a buffer allocation strategy.

**Comment by SanderMertens** [comment]
Moved to alpha 0.2.0 as this is QA related.

**Comment by SanderMertens** [comment]
I'm going to close this issue as for now I don't think it addresses a problem. It is relatively easy to translate the attributes and state to a string (with the corresponding __str functions).

**Comment by jleeothon** [comment]
:+1: 

Maybe I should look back where I needed to serialize state and attributes and consume use the __str function (`cx_bitmask__str`?) instead.

**Comment by SanderMertens** [comment]
Use `cx_attr__str` and `cx_state__str`.

**Comment by jleeothon** [comment]
Thanks!
