### ISSUE TITLE
Add ternary built-in condition variable.

### ISSUE THREAD

**Issue by SanderMertens** [cortexlang/cortex#6]
In ternary expressions often the condition expression is reused in the middle- and right expression. To avoid redundancy (especially with lengthy conditions) the following syntax is proposed:
```Cortex
var object drink = machine.coffee ? ?.cupOf : machine.tea.cupOf;
```
The `?` here is the placeholder for `machine.coffee`. This provides an elegant method of checking for null references.

**Comment by jleeothon** [comment]
"An elegant method of checking for null references"?
Do you mean that
```
var object drink = machine.coffee ? machine.coffee.cupOf : machine.tea.cupOf
```
would fail if `machine.coffee` was null?

**Comment by jleeothon** [comment]
As an idiom for "set value if it's null", we considered the following syntax inspired in ternary operators and shortcut assignment operators:
```
a ?= b
// equivalent to a = a ? a : b
// or if compatible with the above syntax, a = a ? ? : b ***
// looks funny
```

As an extension, we may want "initialize to the first non-null (or non false) value of n values".
```
a ?= b : c
// a = a ? a : (b ? b : c)
// a = a ? ? : (b ? ? : c) ***
// I wonder if parser would handle a = a?? : (b?? c) out of the box

a ?= b : c : d : e
a = a ? ? : (b ? ? : (c ? ? : (d ? ? : e))) ***
```

I wonder what the context variable `?` would mean in the above cases.
In the case of the expanded versions marked ***, the ternary operator is a shortcut for the innermost condition variable.
In the case of the shortcut operator `?=`, however, it sounds as though `?` should *always* be replaced by the left-hand side of the assignment.

**Comment by SanderMertens** [comment]
In hindsight this might not be a very readable mechanism for checking for null.
